import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers/Providers";
import { Toaster } from "@/components/ui/toaster";
import React from "react";
import Custom from "./providers/Custom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MaxUp Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <Custom>{children}</Custom>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
